version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./MySQL:/docker-entrypoint-initdb.d
      - 'mysqldb:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks: 
      - dpm_network
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: local
    

  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - '8086:8086'
      - '8083:8083'
    expose:
      - 8086
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
      - 'influxdb:/var/lib/influxdb'
    networks: 
      - dpm_network
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
  
  # Internal SDC
  sdc1:
    image: "streamsets/datacollector:${SDC_VERSION:-3.8.0}"
    restart: always
    hostname: sdc1
    volumes:
      - 'sdc1:/data'
      - './sdcUserLibraries:/opt/streamsets-datacollector-user-libs'
      - './resources:/resources'
    networks: 
      - dpm_network
    expose:
      - "18630"
    ulimits:
      nofile: 32768
  
  sdc2:
    image: "streamsets/datacollector:${SDC_VERSION:-3.8.0}"
    container_name: sdc.cluster
    restart: always
    volumes:
      - 'sdc2_data:/data'
      - 'sdc2:/etc/sdc'
      - './sdcUserLibraries:/opt/streamsets-datacollector-user-libs'
      - './resources:/resources'
    hostname: ${HOSTNAME}
    networks: 
      - dpm_network
    ports:
      - '18630:18630' 
    ulimits:
      nofile: 32768
  
  sdt:
    image: streamsets/transformer:${SDT_VERSION:-3.9.0-latest}
    container_name: sdt.cluster
    restart: always
    volumes:
      - 'sdt:/etc/sdt'
      - 'sdt_data:/data'
      - './streamsets-transformer-user-libs:/opt/streamsets-transformer-user-libs'
      - './resources:/resources'
    hostname: ${HOSTNAME}
    networks: 
      - dpm_network
    ports:
      - '19630:19630' 
    ulimits:
      nofile: 32768

  sch:
    build:
      context: .
      dockerfile: ./control_hub/Dockerfile
      args:
        - MAIL_ADD=$MAIL_ADD
        - MAIL_PWD=$MAIL_PWD
        - DPM_URL=${DPM_URL:?err}
        - VERSION=${DPM_VERSION:-3.8.0}
    container_name: dpm.cluster
    depends_on:
      - mysql
      - influxdb
      - sdc1
    hostname: dpm.cluster
    networks: 
      - dpm_network
    expose:
      - "18631"
      - "18632"
    ports:
      - '18632:18632'
      - '18631:18631'
      - '587'
      - '465'
    volumes:
      - 'dpm:/data'
      - 'dpm:/etc/dpm'
  
  edge:
    image: streamsets/datacollector-edge:${SDCE_VERSION:-3.8.0}
    container_name: edge.cluster
    hostname: edge.cluster
    networks: 
      - dpm_network
    ports:
      - '18633:18633'
    volumes:
      - 'edge:/opt/datacollector-edge/data'

volumes:
  mysqldb:
  influxdb:
  sdc1:
  sdc2:
  sdc2_data:
  dpm:
  edge:
  sdt:
  sdt_data:

networks:
  dpm_network: