version: '3.1'

volumes:
  db:
    driver: local

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./MySQL:/docker-entrypoint-initdb.d
      - ${volume}/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: local
    

  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - '8086:8086'
      - '8083:8083'
    expose:
      - 8086
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
      - ${volume}/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"

  smtp:
    image: namshi/smtp
    container_name: smtp_relay
    restart: always
    expose: 
      - 25
    ports:
      - "25:25"
  
  sdc1:
    image: 'streamsets/datacollector:latest'
    restart: always
    volumes:
      - '${volume}/sdc1:/data'
    expose:
      - "18630"
  
  sdc2:
    image: 'streamsets/datacollector:latest'
    restart: always
    volumes:
      - '${volume}/sdc2:/data'
    expose:
      - "18630"
    ports:
      - "18630:18630"

  sch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ORACLE_JDK_URL: ${ORACLE_JDK_URL}
        DPM_RMP: ${DPM_RMP}
        MYSQL_CONNECTOR_URL: ${MYSQL_CONNECTOR_URL}
    depends_on:
      - mysql
      - influxdb
      - smtp
      - sdc1
      - sdc2
    links:
      - mysql
      - influxdb
      - smtp
      - sdc1
      - sdc2
    ports:
      - '18631:18631'
    volumes:
      - '${volume}/sch:/data'
