version: '3.1'

volumes:
  db:
    driver: local

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./MySQL:/docker-entrypoint-initdb.d
      - 'mysqldb:/var/lib/mysql'
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: local
    

  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - '8086:8086'
      - '8083:8083'
    expose:
      - 8086
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
      - 'influxdb:/var/lib/influxdb'
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"

  tmail:
    image: vimagick/tmail
    ports:
      - "25:25"
      - "110:110"
    volumes:
      - mail:/var/mail
    environment:
      - MAIL_NAME=domain.org
      - MAIL_PATH=/var/mail
      - MAIL_USER=user
      - MAIL_PASS=pass
    restart: always
  
  # Internal SDC
  sdc1:
    image: 'streamsets/datacollector:latest'
    restart: always
    volumes:
      - 'dc1:/data'
    expose:
      - "18630"
  
  sdc2:
    image: 'streamsets/datacollector:latest'
    restart: always
    volumes:
      - 'dc2:/data'
    expose:
      - "18630"
    ports:
      - "18630:18630"

  sch:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - influxdb
      - tmail
      - sdc1
      - sdc2
    links:
      - mysql
      - influxdb
      - tmail
      - sdc1
      - sdc2
    ports:
      - '18631:18631'
      - '18632:18632'
    volumes:
      - 'ch:/data'
      - 'ch:/etc/dpm'

volumes:
  mysqldb:
  influxdb:
  dc1:
  dc2:
  ch:
  mail: