version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./MySQL:/docker-entrypoint-initdb.d
      - 'mysqldb:/var/lib/mysql'
    networks:
      dpm_network:
        aliases:
          - mysql.emea.cluster
    hostname: mysql.emea.cluster
    environment:
      MYSQL_ROOT_PASSWORD: local
    

  influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
      - 'influxdb:/var/lib/influxdb'
    networks:
      dpm_network:
        aliases:
          - influx.emea.cluster
    hostname: influx.emea.cluster
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
  
  # Internal SDC
  sdc1:
    image: "streamsets/datacollector:${SDC_VERSION:-3.10.1}"
    restart: always
    hostname: sdc1
    volumes:
      - 'sdc1:/data'
      - './sdcUserLibraries:/opt/streamsets-datacollector-user-libs'
      - './resources:/resources'
    networks:
      dpm_network:
        aliases:
          - sdc01.emea.cluster
    hostname: sdc01.emea.cluster
    ulimits:
      nofile: 32768
  
  sdc2:
    image: "streamsets/datacollector:${SDC_VERSION:-3.10.1}"
    container_name: sdc.cluster
    restart: always
    volumes:
      - 'sdc2_data:/data'
      - 'sdc2:/etc/sdc'
      - './sdcUserLibraries:/opt/streamsets-datacollector-user-libs'
      - './resources:/resources'
    networks:
      dpm_network:
        aliases:
          - sdc02.emea.cluster
    hostname: sdc02.emea.cluster
    ports:
      - '18630:18630' 
    ulimits:
      nofile: 32768

  sch:
    build:
      context: .
      dockerfile: ./control_hub/Dockerfile
      args:
        - MAIL_ADD=$MAIL_ADD
        - MAIL_PWD=$MAIL_PWD
        - DPM_URL=${DPM_URL:?err}
        - VERSION=${DPM_VERSION:-3.11.0}
    # restart: always
    environment:
      - DPM_VERSION=${DPM_VERSION:-3.11.0}
    depends_on:
      - mysql
      - influxdb
      - sdc1
    networks:
       dpm_network:
         aliases:
          - sch01.emea.cluster
    hostname: sch01.emea.cluster
    container_name: dpm.cluster
    ports:
      - '18632:18632'
      - '18631:18631'
      - '587'
      - '465'
    volumes:
      - 'dpm:/etc/dpm'
  
  edge:
    image: streamsets/datacollector-edge:${SDCE_VERSION:-3.10.1}
    container_name: edge.cluster
    restart: always
    networks:
      dpm_network:
       aliases:
         - sde01.emea.cluster
    hostname: sde01.emea.cluster
    ports:
      - '18633:18633'
    volumes:
      - 'edge:/opt/datacollector-edge/data'

volumes:
  mysqldb:
  influxdb:
  sdc1:
  sdc2:
  sdc2_data:
  dpm:
  edge:
  sdt:
  sdt_data:

networks:
  dpm_network: